#!/usr/bin/env bash
set -Eeuo pipefail

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
EXTERNAL_SECRET="${ROOT_DIR}/vault/inventory/obsidian-externalsecret.yaml"

usage() {
    cat <<'EOF'
Usage: bash deploy.sh [--dry-run]

Applies the Obsidian note-sync namespace, CouchDB configuration, PVCs,
ExternalSecrets, CouchDB StatefulSet, and -- once the Setup URI exists -- the
materializer Deployment.

  --dry-run   Print the apply order and the remaining manual steps only.
  --help      Show this message.

Before the first deploy, create the Vault secrets. Commands are in
vault/inventory/obsidian-externalsecret.yaml. Nothing has to be pasted into a
version-controlled file: the JWT key material lives in Vault too.

The materializer needs secret/obsidian/livesync (the Setup URI), which can only
be produced by an already-configured device. If that secret is absent this
script still deploys CouchDB and skips the materializer, so the rollout can be
done in two stages.
EOF
}

CLOUDFLARE_NOTE='Cloudflare: repoint the existing obsidian.panghuer.top Public Hostname
    service to http://obsidian-couchdb.obsidian.svc.cluster.local:5984.
    The dashboard is the only place that takes effect: cloudflared runs in
    token mode with no ConfigMap mounted, and the operator never calls the
    Cloudflare API. tunnel-routes.yaml is a record only.'

case "${1:-}" in
    '') ;;
    --dry-run)
        echo 'Preview only; no cluster changes.'
        echo "  1. ${SCRIPT_DIR}/k8s/namespace.yaml"
        echo "  2. ${SCRIPT_DIR}/k8s/couchdb-config.yaml"
        echo "  3. ${SCRIPT_DIR}/k8s/storage.yaml"
        echo "  4. ${EXTERNAL_SECRET}"
        echo '  5. wait for externalsecret/obsidian-couchdb Ready'
        echo "  6. ${SCRIPT_DIR}/k8s/couchdb.yaml"
        echo "  7. ${SCRIPT_DIR}/k8s/materializer.yaml (only if obsidian-livesync is Ready)"
        echo '  8. wait for statefulset/obsidian-couchdb rollout'
        echo
        echo 'Manual, not performed by this script:'
        echo '  - Vault: secret/obsidian/couchdb and secret/obsidian/livesync'
        echo "  - ${CLOUDFLARE_NOTE}"
        echo '  - Onboard the first device by hand, then generate the Setup URI'
        exit 0
        ;;
    --help|-h)
        usage
        exit 0
        ;;
    *)
        echo "Unknown argument: $1" >&2
        usage >&2
        exit 2
        ;;
esac

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 2
fi

command -v kubectl >/dev/null || {
    echo 'kubectl is required.' >&2
    exit 1
}

[[ -f "${EXTERNAL_SECRET}" ]] || {
    echo "Missing ${EXTERNAL_SECRET}. Use a full armbianbegin checkout including panghu_chat." >&2
    exit 1
}

kubectl apply -f "${SCRIPT_DIR}/k8s/namespace.yaml"
kubectl apply -f "${SCRIPT_DIR}/k8s/couchdb-config.yaml"
kubectl apply -f "${SCRIPT_DIR}/k8s/storage.yaml"
kubectl apply -f "${EXTERNAL_SECRET}"

# Only the CouchDB secret is required for this stage. The livesync secret is
# checked separately below, because it cannot exist until a device has been
# configured -- blocking on it here would make a first-stage deploy impossible.
kubectl -n obsidian wait \
    --for=condition=Ready "externalsecret/obsidian-couchdb" \
    --timeout=180s

kubectl apply -f "${SCRIPT_DIR}/k8s/couchdb.yaml"
kubectl -n obsidian rollout status statefulset/obsidian-couchdb --timeout=300s

echo
if kubectl -n obsidian wait \
    --for=condition=Ready "externalsecret/obsidian-livesync" \
    --timeout=15s 2>/dev/null; then
    kubectl apply -f "${SCRIPT_DIR}/k8s/materializer.yaml"
    echo 'Materializer applied.'
else
    cat <<'EOF'
obsidian-livesync is not Ready, so the materializer was NOT applied.

That is expected before the first device has been configured: the Setup URI it
needs can only be generated by an already-configured device. Store it, then run
this script again:

  kubectl -n vault exec -i vault-0 -- vault kv put secret/obsidian/livesync \
    SETUP_URI='obsidian://setuplivesync?...'

  kubectl -n obsidian annotate externalsecret obsidian-livesync \
    force-sync=$(date +%s) --overwrite
EOF
fi

cat <<'EOF'

Manual steps that this script does not perform:

  1. Cloudflare dashboard: repoint the obsidian.panghuer.top Public Hostname
     service to http://obsidian-couchdb.obsidian.svc.cluster.local:5984.
     The dashboard is the only place that takes effect.

  2. Onboard the first device by hand. The JWT settings are inside the CouchDB
     connection dialogue in the plugin, below Custom Headers -- scroll down.
     Then generate the Setup URI from that device and store it as above.

Note that :latest tags with imagePullPolicy: Always do not roll a workload by
themselves; after rebuilding an image run:

  kubectl -n obsidian rollout restart statefulset/obsidian-couchdb
  kubectl -n obsidian rollout restart deploy/obsidian-materializer
EOF
