apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsh-home
  namespace: dsh
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
